from .add_contact import add_contact
from .change_contact import change_contact
from .remove_contact import remove_contact
from .show_contact import show_contact
from .all_contacts import all_contacts
from .birthdays import birthdays
from .add_birthday import add_birthday
from .show_birthday import show_birthday
from .add_email import add_email
from .add_address import add_address
from .show_address import show_address
from .add_note import add_note
from .add_tag import add_tag
from .edit_note import edit_note
from .delete_note import delete_note
from .show_note import show_note
from .search_note import search_note
from .sort_notes_by_tag import sort_notes_by_tag
from .search_contact import search_contact
from .select_contact import select_contact
from .show_all_notes import show_all_notes
from .edit_phone import edit_phone
from .add_phone import add_phone
from .remove_phone import remove_phone
from .remove_address import remove_address
from .remove_birthday import remove_birthday
from .remove_email import remove_email
